export const AuditActions = {
  USER_LOGIN: "USER_LOGIN",
  ORDER_HELD: "ORDER_HELD",
  ORDER_COMPLETED: "ORDER_COMPLETED",
  ORDER_VOIDED: "ORDER_VOIDED",
  ORDER_RETURNED: "ORDER_RETURNED",
  REGISTER_OPENED: "REGISTER_OPENED",
  REGISTER_CLOSED: "REGISTER_CLOSED",
  INVENTORY_ADJUSTED: "INVENTORY_ADJUSTED",
  STOCK_RECEIVED: "STOCK_RECEIVED",
  EXPENSE_CREATED: "EXPENSE_CREATED",
  PRODUCT_CHANGED: "PRODUCT_CHANGED",
  GIFTCARD_ISSUE: "GIFTCARD_ISSUE",
  GIFTCARD_RELOAD: "GIFTCARD_RELOAD",
  GIFTCARD_REDEEM: "GIFTCARD_REDEEM",
  GIFTCARD_ACTIVATED: "GIFTCARD_ACTIVATED",
  GIFTCARD_DEACTIVATED: "GIFTCARD_DEACTIVATED",
  STAFF_CHANGED: "STAFF_CHANGED",
  SETTINGS_CHANGED: "SETTINGS_CHANGED",
} as const;

export type AuditAction = (typeof AuditActions)[keyof typeof AuditActions];
